### ISSUE TITLE
New-PSDCImage issue

### ISSUE THREAD

**Issue by Bednaross** [sanderstad/PSDatabaseClone#18]
Hi there.
I can't make any image.
I always get error: Vhd path cannot be found
![image](https://user-images.githubusercontent.com/37861366/45033302-6dc26d00-b054-11e8-9aa7-9f5d292a0363.png)

I've installed module on the couple of machines with Windows 10 enterprise/ Win Server 2016 Standard editions/Hyper-V feature/ PS 5.1.14  but with no luck.  

Cheers
Rafal

**Comment by sanderstad** [comment]
Does it generate the VHD?

**Comment by Bednaross** [comment]
No,
![image](https://user-images.githubusercontent.com/37861366/45030264-9134ea00-b04b-11e8-9050-487a14eb787a.png)

I've tried JSON and DB config.

**Comment by sanderstad** [comment]
Did you check the credentials of the folder where you're writing it too that it's able to write there?
Make sure the share permissions are set to Everyone - Full Control.
Make sure the NTFS permissions allow the credential you're passing to write to the share

**Comment by Bednaross** [comment]
already checked :
![image](https://user-images.githubusercontent.com/37861366/45030532-74e57d00-b04c-11e8-89e6-01413cb7efee.png)

**Comment by sanderstad** [comment]
Those are the NTFS permissions, how are the share permissions set up?
Be carefull with the everyone full control on the NFS permissions, but you probably already know that.

> btw, since version 0.2.1 you no longer need the hyper-v feature installed, it will not use it anymore.

**Comment by Bednaross** [comment]
Share permissions:
![image](https://user-images.githubusercontent.com/37861366/45032388-f8ee3380-b051-11e8-98a8-2e1a8a7b329f.png)

Now I have completely different error:
 
![image](https://user-images.githubusercontent.com/37861366/45033157-fd1b5080-b053-11e8-98fa-7bdcb8c97f00.png)
