### ISSUE TITLE
Restore-DbaDatabase restore differential - WARNING: [Select-DbaBackupInformation] Fullname property not found

### ISSUE THREAD

**Issue by lsalih** [sanderstad/PSDatabaseClone#34]
I have a need to apply full and differential backup files to restore to a new database name. I am able to restore from the full in norecovery mode under a new name without an issue, however, I get the following error when I apply the differential backup even though I have -continue switch: 

WARNING: [11:18:18][Select-DbaBackupInformation] Fullname property not found. This could mean that a full backup could not be found or the command must be re-run with the -Continue switch.

Any idea how to apply differential and restore to a new name?

Below is the PS script: 

##STEP 1 - Apply FULL with norecovery 
$ServerName='SQLSRVR'
$SourcePath  = 'U:\SQLBACKUP\FULL'
$DatabaseName = "TESTDB"
$Files = Get-ChildItem -Path $SourcePath | sort-object lastwritetime -Descending | select -First 12
$CMD = $Files | Restore-DbaDatabase -SqlInstance $ServerName  -DatabaseName $DatabaseName  -WithReplace -NoRecovery -ReplaceDbNameInFile 
$CMD

##STEP 2 - Apply DIFF with recovery 
#parm initialization
$ServerName='SQLSRVR'
$SourcePath  = 'U:\SQLBACKUP\DIFF'
$DatabaseName = "TESTDB"
$Files = Get-ChildItem -Path $SourcePath | sort-object lastwritetime -Descending | select -First 8
$CMD = $Files | Restore-DbaDatabase -SqlInstance $ServerName  -DatabaseName $DatabaseName  -WithReplace -ReplaceDbNameInFile -Continue
$CMD

Please note that without adding -continue key when I apply the diff restore I get the warning message, and I get the file in use error when I add -continue switch as if it is trying to restore the database to its original database name! Thank you.

**Comment by sanderstad** [comment]
There is probably an easier way to do it.

You know that you can assign multiple paths to the -Path variable?

Also the Restore-DbaDatabase command will find out which files are needed based on the backup header of the backup.

No need to do all the work manually.

 

Could you try to do the following:

 

$ServerName='SQLSRVR'
$SourcePath = 'U:\SQLBACKUP\FULL', 'U:\SQLBACKUP\DIFF'
$DatabaseName = "TESTDB"
Restore-DbaDatabase -Path $SourcePath -SqlInstance $ServerName -DatabaseName $DatabaseName -WithReplace -NoRecovery -ReplaceDbNameInFile



I hope this helps you out

**Comment by sanderstad** [comment]
There is probably an easier way to do it.
You know that you can assign multiple paths to the -Path variable?
Also the Restore-DbaDatabase command will find out which files are needed based on the backup header of the backup.
No need to do all the work manually.

Could you try to do the following:

```powershell
$ServerName='SQLSRVR'
$SourcePath = 'U:\SQLBACKUP\FULL', 'U:\SQLBACKUP\DIFF'
$DatabaseName = "TESTDB"
Restore-DbaDatabase -Path $SourcePath -SqlInstance $ServerName -DatabaseName $DatabaseName -WithReplace -NoRecovery -ReplaceDbNameInFile
```

I hope this helps you out

**Comment by sanderstad** [comment]
BTW, how does this relate to PSDatabaseClone?

**Comment by lsalih** [comment]
Hello,

Two things:
1) I need to pull the most recent 12 files in the full DIR and also pull the most recent 8 files from DIFF dir, I am not seeing from your example how that could be done and
2) You are running in norecovery, how it will mark the new database to recovery after the DIFF is applied.

I have my files in S3 storage and the drives I am using are mapped to the OS through cloudberry, it is not a default SQL backup folders at the destination server. 
That is why I need to run 2 sets of restore, 1st to restore the Full from most recent (weekend), then apply the most recent DIFF from last night.

**Comment by lsalih** [comment]
I apologize, I was looking for dbatools restore-dbadatabase and I mistakenly posted here. Sorry for placing the question under the wrong place.

**Comment by sanderstad** [comment]
No problem. Just create the issue here
https://github.com/sqlcollaborative/dbatools/issues

**Comment by lsalih** [comment]
I followed your recommendation and changed my script, it is all WORKING NOW.. BIG THANKS TO YOU. I removed the -norecovery so the state becomes recovery once the DIFF bkup is applied... Happy day, and many thanks to you YOU! 

$ServerName='SQLSRVR'
$FullPath = Get-ChildItem -Path 'U:\SQLBACKUP\FULL' | sort-object lastwritetime -Descending | select -First 12
$DiffPath = Get-ChildItem -Path 'U:\SQLBACKUP\DIFF' | sort-object lastwritetime -Descending | select -First 8
$DatabaseName = "TESTDB"
Restore-DbaDatabase -Path $FullPath, $DiffPath -SqlInstance $ServerName -DatabaseName $DatabaseName -WithReplace -ReplaceDbNameInFile

**Comment by sanderstad** [comment]
You're welcome, happy to help

**Comment by cds-acaldas** [comment]
@sanderstad Only post I could find with the same error message I'm getting.

IT used to perform a full backup every day and the Restore-DbaDatabase script was working as expected.

`Restore-DbaDatabase -SQLInstance localhost -SqlCredential $SqlCredential -DatabaseName $databaseName -Path "$DestinationFolderPathBase\$databaseName" -WithReplace -EnableException`

Restore-DbaDatabase script is basically used to clone production databases to a development SQL server to work with up-to-date data.

Recently, IT has updated the backup schedule to weekly (Sunday) backup and a daily differential backup.

If I put both the latest full backup (1 file) and the latest differential backup (1 file) in the same folder, Restore-DbaDatabase script works as expected.

However, I was just curious if it is possible to run Restore-DbaDatabase script without the full backup and only using the latest differential backup.

If I do that, I get this error "[Select-DbaBackupInformation] Fullname property not found. This could mean that a full backup could not be found or the command must be re-run with the -Continue switch." even though I use the -Continue switch.

Is it possible to run Restore-DbaDatabase script without the full backup and only using the latest differential backup?
